from __future__ import annotations

from dataclasses import dataclass, field

import pygame

from game import constants as C

OVERWORLD_MAP = """\
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
TGGGGGGGGGGGGGGPPGGGGGGGGGGGGGGT
TGGXXXXXXXGTTGGPPGGGGXXXXXXXGGGT
TGTXXXXXXXGGGGGPPGGGGXXXXXXXGTGT
TGGXXXXXXXGGGGGPPGGGGXXPXXXXGGGT
TGGXXXPXXXGGGGGPPGGGGGGPGGGGGGGT
TGGGGGPGGGGPPPPPPPPPPGGPGGGGGGGT
TPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPT
TGGGGGGGGGGPPPP@PPPPPGGGXXXXXXGT
TGGXXXXXGGGPPPPPPPPPPGGGXXXXXXGT
TGGXXXXXGXXXXXPPPPPPPGGGXPXXXXGT
TGGXXXXXGXXXXXPPPPPPPGGGGPGGGGGT
TGGXXPXXGXXXXXPPPPPPPGGGGPGXXXGT
TGGGGPGGGXPXXXPPPPPPPGGGGPGXXXGT
TGTGGPGGPGPPPPPPPPPPPGGGGPGXPXGT
TPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPT
TGGGGGGGGGGGGGGPPGGGGGGGGGGGGGGT
TGGGGGGGGGGGGGGPPGGGGGGGGGGGGTGT
TGGWWWWWGTGGGGGPPGGGGGGGTGGGTGGT
TGGWWWWWGGGGGGGPPGGGGGGGGGGGGGGT
TGGWWWWWGGEGGGGPPGGGEGGGGGTGGGGT
TGGGGGGGGGGGGGGPPGGGGGGGGGGGGGGT
TGGGGTGGGGGGEGGPPGGGGGEGGGGGGGGT
TGGGGGGTGGGGGGGPPGGGGGGGGGGGGGGT
TGGGGGGGGGGGGGG>>GGGGGGGGGGGGGGT
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
"""

DUNGEON_HUB_MAP = """\
#########################
#SSSSSSSSSSS<SSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#1SSSSSSSSSSSSSSSSSSSSS2#
#1SSSSSSSSSSSSSSSSSSSSS2#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSS@SSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSBBSSSSSSSSSSS#
#SSSSSSSSSSBBSSSSSSSSSSS#
#########################
"""

DUNGEON_ROOM_1_MAP = """\
#########################
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSCCESSSSSSSSSSSSEEESS#
#SSSEEESSSSHSSSSSSSEEESS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSS>#
#SSSSSSSSSSSSSSSSSSSSSS>#
#SSSSSSSSSSSSSSSSSSSSSSS#
#@SSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#########################
"""

DUNGEON_ROOM_2_MAP = """\
#########################
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSCCESSSSRRRSSSSEEESSS#
#SSSEEESSSSEESSSSEEESSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#>SSSSSSSSSSSSSSSSSSSSSS#
#>SSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSS@S#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#SSSSSSSSSSSSSSSSSSSSSSS#
#########################
"""

DUNGEON_BOSS_MAP = """\
LLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLSSSSSSSSSSSSSLLLLLL
LLLLSSSSSSSSSSSSSSSSSLLLL
LLLSSSSSSSSSSSSSSSSSSSLLL
LLSSSSSSSSSSSSSSSSSSSSSLL
LSSSSSSSSSSSSSSSSSSSSSSSL
LSSSSSSSSSSSSSSSSSSSSSSSL
LSSSSSSSSSSSSBSSSSSSSSSSL
LSSSSSSSSSSSSSSSSSSSSSSSL
LSSSSSSSSSSSSSSSSSSSSSSSL
LSSSSSSSSSSSSSSSSSSSSSSSL
LSSSSSSSSSSSSSSSSSSSSSSSL
LLSSSSSSSSSSSSSSSSSSSSSLL
LLLSSSSSSSSSSSSSSSSSSSLLL
LLLLSSSSSSSSSSSSSSSSSLLLL
LLLLLLSSSSSS@SSSSSSLLLLLL
LLLLLLLLSSSSSSSSSLLLLLLLL
LLLLLLLLLLSSSSSLLLLLLLLLL
LLLLLLLLLLL>>>LLLLLLLLLLL
"""


@dataclass
class MapLink:
    transition_id: str
    target_map: str
    target_spawn: str


@dataclass
class MapDefinition:
    map_id: str
    name: str
    layout: str
    links: dict[str, MapLink] = field(default_factory=dict)
    spawn_tiles: dict[str, tuple[int, int]] = field(default_factory=dict)
    is_overworld: bool = False


MAP_DEFINITIONS: dict[str, MapDefinition] = {
    C.MAP_OVERWORLD: MapDefinition(
        map_id=C.MAP_OVERWORLD,
        name="Willow Town",
        layout=OVERWORLD_MAP,
        is_overworld=True,
        links={
            "dungeon_entrance": MapLink("dungeon_entrance", C.MAP_DUNGEON_HUB, "from_overworld"),
        },
        spawn_tiles={"dungeon_entrance": (15, 23)},
    ),
    C.MAP_DUNGEON_HUB: MapDefinition(
        map_id=C.MAP_DUNGEON_HUB,
        name="Dungeon Entrance",
        layout=DUNGEON_HUB_MAP,
        links={
            "from_overworld": MapLink("from_overworld", C.MAP_OVERWORLD, "dungeon_entrance"),
            "door_1": MapLink("door_1", C.MAP_DUNGEON_ROOM_1, "from_hub"),
            "door_2": MapLink("door_2", C.MAP_DUNGEON_ROOM_2, "from_hub"),
            "boss_door": MapLink("boss_door", C.MAP_DUNGEON_BOSS, "from_hub"),
        },
        spawn_tiles={
            "from_overworld": (12, 2),
            "door_1": (2, 4),
            "door_2": (22, 4),
            "boss_door": (12, 14),
        },
    ),
    C.MAP_DUNGEON_ROOM_1: MapDefinition(
        map_id=C.MAP_DUNGEON_ROOM_1,
        name="Dungeon Room I",
        layout=DUNGEON_ROOM_1_MAP,
        links={
            "from_hub": MapLink("from_hub", C.MAP_DUNGEON_HUB, "door_1"),
        },
        spawn_tiles={"from_hub": (22, 10)},
    ),
    C.MAP_DUNGEON_ROOM_2: MapDefinition(
        map_id=C.MAP_DUNGEON_ROOM_2,
        name="Dungeon Room II",
        layout=DUNGEON_ROOM_2_MAP,
        links={
            "from_hub": MapLink("from_hub", C.MAP_DUNGEON_HUB, "door_2"),
        },
        spawn_tiles={"from_hub": (2, 10)},
    ),
    C.MAP_DUNGEON_BOSS: MapDefinition(
        map_id=C.MAP_DUNGEON_BOSS,
        name="Boss Chamber",
        layout=DUNGEON_BOSS_MAP,
        links={
            "from_hub": MapLink("from_hub", C.MAP_DUNGEON_HUB, "boss_door"),
        },
        spawn_tiles={"from_hub": (12, 15)},
    ),
}

CHAR_TO_TILE = {
    "T": C.TILE_WALL,
    "G": C.TILE_GRASS,
    "P": C.TILE_PATH,
    "W": C.TILE_WATER,
    "D": C.TILE_DOOR,
    ".": C.TILE_GRASS,
    "S": C.TILE_STONE,
    "#": C.TILE_DUNGEON_WALL,
    ">": C.TILE_PORTAL,
    "<": C.TILE_PORTAL,
    "1": C.TILE_ROOM_DOOR,
    "2": C.TILE_ROOM_DOOR,
    "B": C.TILE_BOSS_DOOR,
    "L": C.TILE_LAVA,
    "X": C.TILE_HOUSE,
}

TRANSITION_CHARS = {
    "<": "from_overworld",
    "1": "door_1",
    "2": "door_2",
}

ENTITY_MARKERS = {"@", "E", "C", "H", "R", "K"}

RETURN_PORTAL_ID = "from_hub"
BOSS_DOOR_ID = "boss_door"


def get_map_definition(map_id: str) -> MapDefinition:
    return MAP_DEFINITIONS[map_id]
